#
# fig4latex makefile
#

all: fig5.tex fig2.tex fig7.tex fig8.tex fig3.tex fig1.tex fig4.tex fig6.tex

# translation into pstex

fig5.tex: fig5.pdf 
	fig2dev -L pstex_t -p Lecture35-Dinesh/figs/fig5.pdf -m 1 fig5.fig > fig5.tex

fig5.pdf: fig5.eps 
	epstopdf fig5.eps

fig5.eps: fig5.fig 
	fig2dev -L pstex -m 1 fig5.fig > fig5.eps

clean::
	rm -f fig5.tex fig5.eps fig5.pdf


# translation into pstex

fig2.tex: fig2.pdf 
	fig2dev -L pstex_t -p Lecture35-Dinesh/figs/fig2.pdf -m 1 fig2.fig > fig2.tex

fig2.pdf: fig2.eps 
	epstopdf fig2.eps

fig2.eps: fig2.fig 
	fig2dev -L pstex -m 1 fig2.fig > fig2.eps

clean::
	rm -f fig2.tex fig2.eps fig2.pdf


# translation into pstex

fig7.tex: fig7.pdf 
	fig2dev -L pstex_t -p Lecture35-Dinesh/figs/fig7.pdf -m 1 fig7.fig > fig7.tex

fig7.pdf: fig7.eps 
	epstopdf fig7.eps

fig7.eps: fig7.fig 
	fig2dev -L pstex -m 1 fig7.fig > fig7.eps

clean::
	rm -f fig7.tex fig7.eps fig7.pdf


# translation into pstex

fig8.tex: fig8.pdf 
	fig2dev -L pstex_t -p Lecture35-Dinesh/figs/fig8.pdf -m 1 fig8.fig > fig8.tex

fig8.pdf: fig8.eps 
	epstopdf fig8.eps

fig8.eps: fig8.fig 
	fig2dev -L pstex -m 1 fig8.fig > fig8.eps

clean::
	rm -f fig8.tex fig8.eps fig8.pdf


# translation into pstex

fig3.tex: fig3.pdf 
	fig2dev -L pstex_t -p Lecture35-Dinesh/figs/fig3.pdf -m 1 fig3.fig > fig3.tex

fig3.pdf: fig3.eps 
	epstopdf fig3.eps

fig3.eps: fig3.fig 
	fig2dev -L pstex -m 1 fig3.fig > fig3.eps

clean::
	rm -f fig3.tex fig3.eps fig3.pdf


# translation into pstex

fig1.tex: fig1.pdf 
	fig2dev -L pstex_t -p Lecture35-Dinesh/figs/fig1.pdf -m 1 fig1.fig > fig1.tex

fig1.pdf: fig1.eps 
	epstopdf fig1.eps

fig1.eps: fig1.fig 
	fig2dev -L pstex -m 1 fig1.fig > fig1.eps

clean::
	rm -f fig1.tex fig1.eps fig1.pdf


# translation into pstex

fig4.tex: fig4.pdf 
	fig2dev -L pstex_t -p Lecture35-Dinesh/figs/fig4.pdf -m 1 fig4.fig > fig4.tex

fig4.pdf: fig4.eps 
	epstopdf fig4.eps

fig4.eps: fig4.fig 
	fig2dev -L pstex -m 1 fig4.fig > fig4.eps

clean::
	rm -f fig4.tex fig4.eps fig4.pdf


# translation into pstex

fig6.tex: fig6.pdf 
	fig2dev -L pstex_t -p Lecture35-Dinesh/figs/fig6.pdf -m 1 fig6.fig > fig6.tex

fig6.pdf: fig6.eps 
	epstopdf fig6.eps

fig6.eps: fig6.fig 
	fig2dev -L pstex -m 1 fig6.fig > fig6.eps

clean::
	rm -f fig6.tex fig6.eps fig6.pdf


